version: 3.0.{build}
image: ubuntu
clone_depth: 2

services:
  - docker

pull_requests:
  do_not_increment_build_number: true

init:
  - git config --global core.autocrlf input

environment:
  UI_DOCKER_IMAGE: ui-ci

build_script:
  - docker build --target testrunner -t exceptionless:test .
  - docker run -e APPVEYOR_API_URL --net=host exceptionless:test

after_build:
  - docker build --build-arg UI_VERSION=$APPVEYOR_BUILD_VERSION --target ui -t $UI_DOCKER_IMAGE .
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  - |
    for tag in {$APPVEYOR_BUILD_VERSION,latest}; do
      docker tag $UI_DOCKER_IMAGE exceptionless/$UI_DOCKER_IMAGE:$tag
      docker push exceptionless/$UI_DOCKER_IMAGE:$tag
    done

notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: GniMpFE62HprSyQNQoej/VSBnxn2GNnTrca3BnF8+ikMdqduO4Ts4t297teZF6wDAmGwnOtXusctUla8+WxLFkIztvVCS2Z1RG/DvEDYoc0=
